### ISSUE TITLE
Milestone 3 Checklist

### ISSUE THREAD

**Issue by almas2019** [STAT547-UBC-2019-20/team11_akhan#18]
- [ ] Task 1. Perform your linear regression in a new script (20%)

- - [x] You should create a new script and put it in your scripts directory
- - [x] This script should do your linear regression, and any subsequent explorations and analyses you choose to do
- - [x] Export any plots you want to include in your final report as an image (to the images directory)
- - [x] Export your model object to an RDS file so you can load this file in your final report and use the tidy, augment, or glance functions from the broom package to reference the model’s statistical findings
- - [x] Don’t forget to add a line in the Usage section on how to use this script

- [x] Task 2: Complete your final report and knit it using a script (15%)
- - [x] Write a final script that knits your DRAFT of your final report (an Rmarkdown file) to an HTML and PDF file.

Your script should:
- - [x] Live in the scripts directory
- - [x] Knit the final report Rmd file so that it exports an HTML and PDF file.
 - - [x] Run without any intervention from the user after running the script from a terminal/command prompt
- - [x] Print a helpful message to the terminal informing the user that the script has completed successfully

Guidelines for your final project:

- - [x] Be written in Rmarkdown and should not have any “hard-coded” numbers and values
        Use r code chunks or inline r code)
- - [x] Load an RDS file from your analysis script and report the relevant results of the statistical analysis
- - [x] Have an introduction/motivation and description of research question
- - [x] Have a section describing your dataset (EDA); make sure you import pngs from the images directory rather than creating them again!
- - [x] Have a section for your analysis methods (linear regression)
 - - [x] Have a section for your results
 - - [x] Have a section for your discussion/conclusion
    You can liberally borrow from your milestone1 EDA, particularly the introduction/motivation

- [x] Task 3. Automate your pipeline with MAKE (40%)

- - [x] Write another script, a Makefile (literally called Makefile), to act as a driver script to rule them all. This script should run the others in sequence, specifying filenames, paths, and other neccessary commandline arguments.

This script should:
- - [x] live in the project’s root directory and be named Makefile
- - [x] be well documented (using the project README and comments inside the Makefile to explain what each section does and how to use it)
- - [ ] have an all: target so that you can easily run the entire analysis from top to bottom by running make all at the command line
- - [ ] have a clean: target so that you can easily “undo” your analysis by running make clean at the command line

- [ ] Task 4: Instructions to reproduce your analysis (10%)

- - [ ] Your final task for this milestone is to add a USAGE section in your project README so someone can completely reproduce your analysis from start to finish. 
This section should have two subsections, 
- - [ ] one for running the analysis using GNU MAKE, and the other for running each script individually. 
- - [ ] You should also list all packages and dependencies required for your project. What level of reproducibility should you expect? Well, imagine if someone clones your repository, deletes all the files in every directory except your README, the scripts and docs directory - could they follow both sets of instructions in the USAGE section to reproduce your final report?

Usage instructions for running scripts individually

 - - [ ] This section should largely be the same as what you had in milestone_02, just updated if your scripts changed.
- - [ ] It’s a good idea to provide instructions for running each script individually in case people do not have MAKE installed on their systems and want to reproduce your analyses.
- - [ ] IMPORTANT: You should make sure this section is complete and correct ASAP so your classmates that are reviewing your project are able to run your analysis.

Usage instructions for GNU MAKE

- - [ ] All possible options for your Makefile (make clean, make all, etc…) should be well documented using both the project README and comments inside the Makefile to explain what each section does and how to use it.
