### ISSUE TITLE
Feedbacks Milestone 3

### ISSUE THREAD

**Issue by sirine-chahma** [STAT547-UBC-2019-20/team11_akhan#22]
Great work, and very nice report! Here are some suggestions to improve your work : 

- Try to not display your chunks of code in your final report (use `echo=FALSE` when you define your chunks of code)
- Put the plot of your linear model 'Grade vs workday_alc' (and maybe the one of `Grade vs weekend_alc` too) in your `Methods` section.
- Your `finalReport.Rmd` file should be in the `docs`  folder
- Try to delete the `lm(...)` lines that are under your plots in the `Residual plots ` part
- Try to say explicitly  what your p-values are in the text that you write when you analyse your model, but don't write those values by hand, try to extract them from your code
- Give an interpretation of the coefficients of your model that you judge meaningful : say what those coefficients are, and what they mean (for example the -1.16 estimate that corresponds to `workday_alc` .

But great work!

**Comment by almas2019** [comment]
Hello @sirine-chahma Thank you for your feedback, I will try to incorporate most of it this week. I have one question, for your second point

> - Put the plot of your linear model 'Grade vs workday_alc' (and maybe the one of Grade vs weekend_alc too) in your Methods section. 
Apologies, but I am not sure which plots these are, were these the ones I mentioned in the issues but didn't include in the final report?

**Comment by sirine-chahma** [comment]
As you decided to use a model with interaction, your plot will have 2 lines : one for the workdays alcohol consumption and one for the weekend alcohol consumption. But yes, basically your plot will be the one that you put in the issue, but there will be a second line.

**Comment by almas2019** [comment]
Hi Sirine, Im having trouble making an interaction plot so I decided to just include a simple plot with 1 variable for now and maybe work on the interaction plot in the coming week?
Thank you,
-Almas

On Mar. 24, 2020 3:10 p.m., sirine-chahma <notifications@github.com> wrote:

As you decided to use a model with interaction, your plot will have 2 lines : one for the workdays alcohol consumption and one for the weekend alcohol consumption. But yes, basically your plot will be the one that you put in the issue, but there will be a second line.

**Comment by sirine-chahma** [comment]
Sure, no problem! If you have any question about how to do the plot with the two lines, you can ask me :)

**Comment by almas2019** [comment]
@sirine-chahma  I forgot to include that this is the feedback that I currently addressed:

- [ ] Try to not display your chunks of code in your final report (use echo=FALSE when you define your chunks of code)
- [ ] Your finalReport.Rmd file should be in the docs folder
- [ ] Try to delete the lm(...) lines that are under your plots in the Residual plots part
- [ ] Try to say explicitly what your p-values are in the text that you write when you analyse your model, but don't write those values by hand, try to extract them from your code

- [ ] Put the plot of your linear model 'Grade vs workday_alc' (and maybe the one of Grade vs weekend_alc too) in your Methods section. --> for this one I included a plot below: 

![image](https://raw.githubusercontent.com/STAT547-UBC-2019-20/team11_akhan/master/images/Linear_Reg_Plot_Final_Grade_vs_Weekend_Alcohol_and%20Workday_Alcohol.png)

Thank you!

**Comment by almas2019** [comment]
As well this is the feedback I will try to address with future work:
- [ ] Give an interpretation of the coefficients of your model that you judge meaningful : say what those coefficients are, and what they mean (for example the -1.16 estimate that corresponds to workday_alc .

- [ ] Create an interaction plot of the 2 alcohol variables
