### ISSUE TITLE
Work for Milestone 6

### ISSUE THREAD

**Issue by almas2019** [STAT547-UBC-2019-20/team11_akhan#41]
TA feedback from Issue #39 
- [x] Explain how to run your app in the README file (say that you have to run Rscript app.R in the terminal,...)
- [x] Give the link to find the dataset in you dashboard.
- [x] In your Analysis mode in the Pick the Factor to colour by dropdown menu, I would add a None option, to only do the linear regression between the response and the x-variable (without splitting it in two).

From #29 Future Work 

- [x] Create Readmes in subfolders

From Milestone 6: 

- [x] You should take this opportunity to clean up your repository and make it ready for public release. 
- [x] Close stale issues - If your folder structure is messy or confusing, clean it up and re-organize it 

- [x] Make sure your app is complete, functions correctly, and does what you want it to.

- [x] you should deploy your app on heroku so that it is publicly accessible. In your README, please include the Heroku app link and clearly mark it so that we can find it!

- [x] As part of this task, in addition to a correctly deployed app, we will also check the following files: - apt-packages - app.json - heroku.yml - init.R - Dockerfile

**Comment by almas2019** [comment]
Finished this
